blazesym: update v0.1.0-3-gd954f73 -> v0.2.0 and fix implicit autorefs
Rust now enables the dangerous_implicit_autorefs lint by default, which
breaks blazesym builds. This updates the submodule to v0.2.0 and changes
the code to explicitly dereference raw pointers, removing those errors.
It also renames the `cheader` feature to `generate-c-header` and the new
crate naming for the C API (package and library).

Reference blazesym commits:
a6334a6 Rename `cheader` feature to `generate-c-header`
5c0b6e3 Introduce blazesym-c crate

This makes blazesym build successfully with current Rust toolchains.
Tested on Debian forky (using rustup) with:
* rustc 1.90.0 (1159e78c4 2025-09-14)
* stable-aarch64-unknown-linux-gnu (active, default)
* 1.82.0-aarch64-unknown-linux-gnu

blazesym errors with submodule commit
d954f73867527dc75025802160c759d0b6a0641f blazesym (v0.1.0-3-gd954f73):

error: implicit autoref creates a reference to the dereference of a
raw pointer
    --> src/lib.rs:1024:42
     |
1024 |                     file_name: from_cstr((*c).params.elf.file_name),
     |                                          ^^-^^^^^^^^^^^^^^^^^^^^^^
     |                                            |
     |                                            this raw pointer has
type `*const sym_src_cfg`
     |
     = note: creating a reference requires the pointer target to be
valid and imposes aliasing requirements
     = note: references are created through calls to explicit
`Deref(Mut)::deref(_mut)` implementations
     = note: `#[deny(dangerous_implicit_autorefs)]` on by default
help: try using a raw pointer method instead; or if this reference is
intentional, make it explicit
     |
1024 |                     file_name: from_cstr((&(*c).params.elf).file_name),
     |                                          ++               +

1046 |                     pid: if (&(*c).params.process).pid > 0 {
     |                             ++                   +

Signed-off-by: Daniel Gomez <da.gomez@samsung.com>